---
title: "Journal (reproducible report)"
author: "Ashweej Rao Myerpady"
date: "2020-11-05"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

**IMPORTANT:** You can delete everything in here and start fresh. You might want to start by not deleting anything above this line until you know what that stuff is doing.




Last compiled: `r Sys.Date()`




# Intro To Tidyverse
##challenge part 1
```{r}

# SALES ANALYSIS ----

# 1.0 Load libraries ----
library(tidyverse)
library(readxl)
# 2.0 Importing Files ----
bikes_tbl      <- read_excel(path = "00_data/01_bike_sales/01_raw_data/bikes.xlsx")
orderlines_tbl <- read_excel("00_data/01_bike_sales/01_raw_data/orderlines.xlsx")
bikeshops_tbl  <- read_excel("00_data/01_bike_sales/01_raw_data/bikeshops.xlsx")

# 3.0 Examining Data ----
#glimpse(orderlines_tbl)

# 4.0 Joining Data ----
bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

# 5.0 Wrangling Data ----

challenge_bike_orderlines_wrangled_tbl  <- bike_orderlines_joined_tbl %>%
  separate(col    = location,
           into   = c("city", "state"),
           sep    = ", ") %>%
  mutate(total.price = price * quantity) %>%
  
  select(-...1, -gender) %>%
  
  select(-ends_with(".id")) %>%
  
  bind_cols(bike_orderlines_joined_tbl %>% select(order.id)) %>% 
  
  select(order.id, contains("order"), contains("model"), contains("category"),
         price, quantity, total.price,state,city,
         everything()) %>%
  
  rename(bikeshop = name) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_"))


# 6.0 Business Insights ----
  
library(lubridate)

sales_by_state_tbl <- challenge_bike_orderlines_wrangled_tbl %>%
  select(state, total_price) %>%
  
  group_by(state) %>% 
  summarize(sales = sum(total_price))%>%
mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                   decimal.mark = ",", 
                                   prefix = "", 
                                   suffix = " €"))
sales_by_state_tbl %>%
  ggplot(aes(x = state, y = sales)) +
  geom_col(fill = "#2DC6D6") + # Use geom_col for a bar plot
  geom_label(aes(label = sales_text)) + # Adding labels to the bars
  geom_smooth(method = "lm", se = FALSE) + # Adding a trendline
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title    = "Revenue by state",
    subtitle = "comparison",
    x = "", # Override defaults for x and y
    y = "Revenue"
  )


# 6.1 Sales by Year and location ----
  
sales_by_year_state_tbl <- challenge_bike_orderlines_wrangled_tbl %>%
  
  # Select columns and add a year
  select(order_date, total_price, state) %>%
  mutate(year = year(order_date)) %>%
  
  # Group by and summarize year and main catgegory
  group_by(year, state) %>%
  summarise(sales = sum(total_price)) %>%
  ungroup() %>%
  
  # Format $ Text
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

#sales_by_year_state_tbl  
# Step 1 - Manipulate

# Step 2 - Visualize
sales_by_year_state_tbl %>%
  
  # Set up x, y, fill
  ggplot(aes(x = year, y = sales, fill = state)) +
  
  # Geometries
  geom_col() + # Run up to here to get a stacked bar plot
  
  # Facet
  facet_wrap(~ state) +
  
  # Formatting
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by year and state",
    subtitle = "A comparison",
    fill = "Main category" # Changes the legend name
  )  
  
  
```


#Data Acquisistion

##challenge part 1 - spotifyr web api
```{r}

library(spotifyr)


library(tidyverse)
library(knitr)


rock_artists<-get_genre_artists(
  genre = "rock",
  
  authorization = get_spotify_access_token()
)
rock_artists 
```


##challenge part 2 - competitor web scraping
```{r}

# WEBSCRAPING ----

# 1.0 LIBRARIES ----

library(tidyverse) # Main Package - Loads dplyr, purrr, etc.
library(rvest)     # HTML Hacking & Web Scraping
library(xopen)     # Quickly opening URLs
library(jsonlite)  # converts JSON files to R objects
library(glue)      # concatenate strings
library(stringi)   # character string/text processing
library (dplyr)

url_home = "https://www.rosebikes.de/fahrräder/mtb"


html_home         <- read_html(url_home)

type_name <- html_home %>%
  html_nodes(css = ".catalog-category-bikes__title-text")%>%
  html_text()
               
type_price <-  html_home %>%
  html_nodes(css = ".catalog-category-bikes__price-title")%>%
  html_text()

name_list<-c()

price_list<-c()
#type_name_list= str_split(type_name," ")
for (i in type_name){
  
 elem<-str_extract(i,".+(?=\\n)")
 name_list<-c(name_list,elem)

}


for (i in type_price){
  
  elem<-str_extract(i,"(?<= ).+(?=\\S)")
  price_list<-c(price_list,elem)
  
}

#bike_table<- enframe(name =

#df <- ldply (price_list, data.frame)

bike_price_table<-data.frame(name_list,price_list)

bike_price_table
#a<-enframe(c(name=name_list,values=price_list))
```











